name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable

      - name: Set up Rust targets
        if: matrix.os == 'macos-14' 
        run: rustup target add aarch64-apple-darwin
    
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.20.2"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0